# Automation of EBS Snapshot tool.
# Requirements:
# 1. AWS Cloud Formation Service
#
# Roll-out steps:
# 1. Zip the https://github.com/atimush/aws/blob/master/EC2/ebs_snapshots.py file
# 2. Create S3 bucket and upload to archive.
# 3. Adjust/Update the 'S3Bucket' and 'S3Key' values in the 'EBSFunction' Resource and job frequency as 'ScheduleExpression'.
# 4. Create and run a CF Stack as defined below.
#
# IMPORTANT:
# 1. CF Stack will require additional validation to use the IAM Grants.
# Confirmation (Check Box) is mandatory.
#
# author: 'Andrei Timush'

AWSTemplateFormatVersion: "2010-09-09"
Description: "EBS Snapshot Provisioning"
Resources:
  LambdaEBSRole:
    Description: "Create Lambda EBS Role"
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "Lambda-ebs-snapshots"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "logs:*"
                Resource: "arn:aws:logs:*:*:*"
              -
                Effect: "Allow"
                Action: "ec2:Describe*"
                Resource: "*"
              -
                Effect: "Allow"
                Action:
                  - "ec2:CreateSnapshot"
                  - "ec2:DeleteSnapshot"
                  - "ec2:CreateTags"
                  - "ec2:ModifySnapshotAttribute"
                  - "ec2:ResetSnapshotAttribute"
                Resource: "*"
      RoleName: "ebs-snapshots"
  EBSFunction:
    Description: "Create Lambda EBS Snapshot Function"
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: "timush-lambda-functions"
        S3Key: "ebs_snapshots.zip"
      FunctionName: "ebs-snapshots"
      Handler: "ebs_snapshots.lambda_handler"
      Role: !GetAtt LambdaEBSRole.Arn
      Runtime: "python2.7"
      Timeout: 60
  ScheduledRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Automatic EBS snapshotting job"
      ScheduleExpression: "rate(5 minutes)"
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt EBSFunction.Arn
          Id: "ebs-snapshots"
  PermissionForEventsToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName:
        Ref: "EBSFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt ScheduledRule.Arn